name: OpenPolicyAgent Compliance Checks 

on: [pull_request]

jobs:
  Compliance_Check:

    container:
      image: gcr.io/cdssnc/azure-cli:latest
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: "${{secrets.CLIENT_ID}}"
      ARM_SUBSCRIPTION_ID: "${{secrets.SUBSCRIPTION_ID}}"
      ARM_TENANT_ID: "${{secrets.TENANT_ID}}"
      ARM_CLIENT_SECRET: "${{secrets.CLIENT_SECRET}}"

    steps:
    - uses: actions/checkout@v1
    - name: 'Terraform Init & Validate'
      run: terraform init  -backend-config=backend.tfvars
    - name: 'Terraform Validate'
      run: terraform validate
    - name: 'Terraform Plan'
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:  | 
        function stripColours {
          echo "${1}" | sed 's/\x1b\[[0-9;]*m//g'
        }
        tfoutput=$(terraform plan  -out tf.plan)
        tfcleared=$(stripColours "${tfoutput}")
        jq -n --arg msg "$tfcleared" '{body : $msg }' > tf.out.txt
        curl \
          -X POST \
          $URL \
          -H "Content-Type: application/json" \
          -H "Authorization:token $GITHUB_TOKEN" \
          -d @tf.out.txt
        
    - name: 'Generate JSON file'
      run:  terraform show -json tf.plan > tf.plan.json
    - name: Configuration Test
      uses: instrumenta/conftest-action@master
      with:
        files: tf.plan.json