name: OpenPolicyAgent Compliance Checks 

on: [pull_request]

jobs:
  Compliance_Check:

    container:
      image: gcr.io/cdssnc/azure-cli:0.0.3
    runs-on: ubuntu-latest

    env:
      TF_VAR_infra-version: "v0.0.0"
      ARM_CLIENT_ID: "${{secrets.CLIENT_ID}}"
      ARM_SUBSCRIPTION_ID: "${{secrets.SUBSCRIPTION_ID}}"
      ARM_TENANT_ID: "${{secrets.TENANT_ID}}"
      ARM_CLIENT_SECRET: "${{secrets.CLIENT_SECRET}}"

    steps:
    - uses: actions/checkout@v1
    - name: 'Terraform Init'
      run: terraform init  -backend-config=backend.tfvars
    - name: 'Terraform Validate'
      run: terraform validate
    - name: 'Terraform Plan'
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:  ./terraform_plan.sh
    - name: 'Generate JSON file'
      run:  terraform show -json tf.plan > tf.plan.json
    - name: Configuration Test
      uses: instrumenta/conftest-action@master
      with:
        files: tf.plan.json