name: OpenPolicyAgent Compliance Checks 

on: [pull_request]

jobs:
  Compliance_Check:

    container:
      image: gcr.io/cdssnc/azure-cli:0.0.3
    runs-on: ubuntu-latest

    env:
      TF_VAR_infra-version: "v0.0.0"
      ARM_CLIENT_ID: "${{secrets.CLIENT_ID}}"
      ARM_SUBSCRIPTION_ID: "${{secrets.SUBSCRIPTION_ID}}"
      ARM_TENANT_ID: "${{secrets.TENANT_ID}}"
      ARM_CLIENT_SECRET: "${{secrets.CLIENT_SECRET}}"

    steps:
    - uses: actions/checkout@v1
    - name: 'Terraform Init, Validate, Plan, and generate json file'
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        cd cppd_medical_report
        terraform init  -backend-config=backend.tfvars
        terraform validate
        ./terraform_plan.sh
        terraform show -json tf.plan > tf.plan.json
    - name: Configuration Test
      uses: instrumenta/conftest-action@master
      with:
        files: ./cppd_medical_report/tf.plan.json