name: OpenPolicyAgent Compliance Checks 

on: [push]

jobs:
  Compliance_Check:

    container:
      image: gcr.io/cdssnc/azure-cli:latest
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: "${{secrets.CLIENT_ID}}"
      ARM_SUBSCRIPTION_ID: "${{secrets.SUBSCRIPTION_ID}}"
      ARM_TENANT_ID: "${{secrets.TENANT_ID}}"
      ARM_CLIENT_SECRET: "${{secrets.CLIENT_SECRET}}"

    steps:
    - uses: actions/checkout@v1
    - name: 'Terraform Init & Validate'
      run: terraform init  -backend-config=backend.tfvars
    - name: 'Terraform Validate'
      run: terraform validate
    - name: 'Terraform Plan'
      env:
        URL: ${{ github.event.issue.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:  | 
        echo "Printing out URL"
        echo "$URL"
    - name: 'Generate JSON file'
      run:  terraform show -json tf.plan > tf.plan.json
    - name: Configuration Test
      uses: instrumenta/conftest-action@master
      with:
        files: tf.plan.json