name: Terraform Security Scan

on: [push]

jobs:
  Terraform_Security_Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Terraform security scan
      uses: triat/terraform-security-scan@v1